server:
  port: 9000
spring:
  rabbitmq:
    addresses: rabbitmq:5672
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        input:
          destination: axon-output
          group: school-events
logging:
  level:
    org:
      springframework: DEBUG